[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "serve . -p 3999"
  targetPort = 3999
  port = 8888
  publish = "."
  functions = "netlify/functions"
  autoLaunch = false
  
  [[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
